# Generated by Django 2.2 on 2019-06-07 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GenyTreeApp', '0002_auto_20190607_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='child',
            field=models.ManyToManyField(null=True, related_name='parents', through='GenyTreeApp.Child', to='GenyTreeApp.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='couple',
            field=models.ManyToManyField(null=True, related_name='couples', through='GenyTreeApp.Union', to='GenyTreeApp.Person'),
        ),
    ]
