# Generated by Django 2.2 on 2019-06-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenyTreeApp', '0003_auto_20190607_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='child',
            field=models.ManyToManyField(related_name='parents', through='GenyTreeApp.Child', to='GenyTreeApp.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='couple',
            field=models.ManyToManyField(related_name='couples', through='GenyTreeApp.Union', to='GenyTreeApp.Person'),
        ),
    ]
