# Generated by Django 2.2 on 2019-06-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenyTreeApp', '0004_auto_20190607_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
