# Generated by Django 2.2 on 2019-06-11 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GenyTreeApp', '0005_auto_20190611_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('edit_person', 'Edit person'),)},
        ),
    ]
