# Generated by Django 2.2 on 2019-06-11 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GenyTreeApp', '0006_auto_20190611_0209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
    ]
