# Generated by Django 2.2 on 2019-06-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenyTreeApp', '0007_auto_20190611_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='generation',
            field=models.SmallIntegerField(null=True),
        ),
    ]
